name: CONDA-LAB-DMS
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      # GUI
      - PyQt6==6.9.1
      - PyQt6-Qt6==6.9.2
      - PyQt6_sip==13.10.2
      - qt-material==2.17

      # PDF & Images
      - reportlab==4.4.3
      - pillow==11.3.0
      - pdf2image==1.17.0

      # Database
      - psycopg2-binary==2.9.10
      - SQLAlchemy==2.0.43
      - dbfread==2.0.7
