name: lab_dms
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - altgraph==0.17.4
      - asttokens==3.0.0
      - attrs==25.3.0
      - auto-py-to-exe==2.47.0
      - backcall==0.2.0
      - beautifulsoup4==4.13.5
      - bleach==6.2.0
      - bottle==0.13.4
      - bottle-websocket==0.2.9
      - certifi==2025.8.3
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - colorama==0.4.6
      - dbfread==2.0.7
      - decorator==5.2.1
      - defusedxml==0.7.1
      - docopt==0.6.2
      - Eel==0.18.2
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - future==1.0.0
      - gevent==25.8.2
      - gevent-websocket==0.10.1
      - greenlet==3.2.4
      - idna==3.10
      - importlib_resources==6.5.2
      - ipython==8.12.3
      - jedi==0.19.2
      - Jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter_client==8.6.3
      - jupyter_core==5.8.1
      - jupyterlab_pygments==0.3.0
      - MarkupSafe==3.0.2
      - matplotlib-inline==0.1.7
      - mistune==3.1.4
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - packaging==25.0
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pdf2image==1.17.0
      - pefile==2023.2.7
      - pickleshare==0.7.5
      - pillow==11.3.0
      - pip-check-reqs==2.5.5
      - pipreqs==0.5.0
      - platformdirs==4.4.0
      - prompt_toolkit==3.0.52
      - psycopg2==2.9.10
      - psycopg2-binary==2.9.10
      - pure_eval==0.2.3
      - pycparser==2.23
      - Pygments==2.19.2
      - pyinstaller==6.16.0
      - pyinstaller-hooks-contrib==2025.8
      - pyparsing==3.2.4
      - PyQt6==6.9.1
      - PyQt6-Qt6==6.9.2
      - PyQt6_sip==13.10.2
      - python-dateutil==2.9.0.post0
      - pywin32==311
      - pywin32-ctypes==0.2.3
      - pyzmq==27.1.0
      - qt-material==2.17
      - referencing==0.36.2
      - reportlab==4.4.3
      - requests==2.32.5
      - rpds-py==0.27.1
      - setuptools==80.9.0
      - six==1.17.0
      - soupsieve==2.8
      - SQLAlchemy==2.0.43
      - stack-data==0.6.3
      - tinycss2==1.4.0
      - tornado==6.5.2
      - traitlets==5.14.3
      - typing_extensions==4.15.0
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - webencodings==0.5.1
